add stdio redirection example
DLR-FT/a653rs-linux pull request #119
Opened 2024-06-18 12:30 UTC by sevenautumns

### 🚀 Features

- Add stdio redirection example

### 🚜 Refactor

- Reorganize examples
- Remove unused dependencies

2024-06-19 14:59 UTC, wucke13 commented
@sevenautumns please rebase

2024-06-19 15:03 UTC, wucke13 approved these changes

2024-06-20 07:50 UTC, dadada commented on examples/redirect_stdio/src/main.rs
> +        // TODO wait for https://github.com/DLR-FT/a653rs/issues/22 to be fixed
Steht als completed drin.

2024-06-20 07:52 UTC, dadada commented on flake.nix
> +              tmpdir=$(mktemp -d -t redirect_stdio.XXXXXXXXXX)
Should trap to remove the directory automatically on SIGTERM etc.

2024-06-20 07:53 UTC, dadada commented on flake.nix
> +              tmpdir=$(mktemp -d -t redirect_stdio.XXXXXXXXXX)
Or even better just put the output somewhere in the current working directory, incase we want to inspect it. No reason to put it in tmpfs?

2024-06-20 07:56 UTC, dadada commented on examples/redirect_stdio/src/main.rs
> +    nix::unistd::dup2(new.as_raw_fd(), stdio.as_raw_fd())?;
Can you close stdin afterward?

2024-06-20 07:58 UTC, dadada requested changes
I'm against using tmpfs in the example. It is more complicated than needed.

2024-06-20 08:36 UTC, dadada approved these changes

2024-06-20 08:36 UTC, merged