core: output the kill duration constant
DLR-FT/a653rs-linux pull request #74
Opened 2023-06-23 07:15 UTC by emilengler

2023-06-23 10:49 UTC, sevenautumns requested changes

2023-06-23 10:49 UTC, sevenautumns commented on core/src/cgroup.rs
>                  trace!("Killed with a 1s timeout");
also here

2023-06-29 08:14 UTC, emilengler commented
done

2023-06-30 11:23 UTC, wucke13 approved these changes

2023-06-30 11:23 UTC, merged